query getContacts {
    ResPartner {
        id
        name
        category_id {
            name
        }
        user_id {
            name
        }
        parent_id {
            id
            ...ContactData
            parent_id {
                id
                ...ContactData
            }
        }
    }
}

fragment ContactData on ResPartner {
  name
  email
}
